server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://<yourRDSEndPoint>:3306/<UseYourDATABASE>
    username: admin #For testing
    password: Passw0rd!123 #For testing
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true